ALTER TABLE game 
	ADD CONSTRAINT fk_game_genre FOREIGN KEY (genreid) REFERENCES [genre](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE game 
	ADD CONSTRAINT fk_game_dev FOREIGN KEY (devid) REFERENCES [dev](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE dev 
	ADD CONSTRAINT fk_dev_player FOREIGN KEY (playerid) REFERENCES [player](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE player 
	ADD CONSTRAINT fk_player_icon FOREIGN KEY (iconid) REFERENCES [icon](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE player 
	ADD CONSTRAINT fk_player_stat FOREIGN KEY (statid) REFERENCES [stat](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE gameplayer 
	ADD CONSTRAINT fk_join_game FOREIGN KEY (gameid) REFERENCES [game](id)
	ON DELETE NO ACTION
	ON UPDATE CASCADE;

GO

ALTER TABLE gameplayer 
	ADD CONSTRAINT fk_join_player FOREIGN KEY (playerid) REFERENCES [player](id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

GO

ALTER TABLE statachi 
	ADD CONSTRAINT fk_join_stat FOREIGN KEY (statid) REFERENCES [stat](id)
	ON DELETE NO ACTION
	ON UPDATE CASCADE;

GO

ALTER TABLE statachi 
	ADD CONSTRAINT fk_join_achi FOREIGN KEY (achiid) REFERENCES [achi](id)
	ON DELETE NO ACTION
	ON UPDATE CASCADE;

GO
