ALTER TABLE game 
	ADD CONSTRAINT fk_game_genre FOREIGN KEY (genreid) REFERENCES [genre](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE game 
	ADD CONSTRAINT fk_game_dev FOREIGN KEY (devid) REFERENCES [dev](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE dev 
	ADD CONSTRAINT fk_dev_player FOREIGN KEY (playerid) REFERENCES [player](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE player 
	ADD CONSTRAINT fk_player_icon FOREIGN KEY (iconid) REFERENCES [icon](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE player 
	ADD CONSTRAINT fk_player_stat FOREIGN KEY (statid) REFERENCES [stat](id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO
