CREATE TABLE game (
	id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	title NVARCHAR(100) NOT NULL,
	creation DATE NOT NULL,
	score BIGINT NOT NULL CONSTRAINT scorelimit CHECK (score between 0 and 100),
	picture VARBINARY(max) NOT NULL,
	genreid BIGINT NOT NULL,
	devid BIGINT NOT NULL
);

GO

CREATE TABLE dev (
	id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	title NVARCHAR(100) NOT NULL,
	picture VARBINARY(max) NOT NULL,
	playerid BIGINT NOT NULL
);

GO

CREATE TABLE player (
	id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	title NVARCHAR(100) NOT NULL,
	creation DATE NOT NULL,
	iconid BIGINT NOT NULL,
	statid BIGINT NOT NULL
);

GO

CREATE TABLE stat (
	id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	timespent BIGINT NOT NULL,
	perfectgame BIGINT NOT NULL,
	acclevel BIGINT NOT NULL CONSTRAINT maxlevel CHECK (acclevel between 1 and 80),
	moneyspent BIGINT NOT NULL
);

GO

CREATE TABLE genre (
	id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	title NVARCHAR(100) NOT NULL
);

GO

CREATE TABLE icon (
	id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	picture VARBINARY(max) NOT NULL
);

GO

CREATE TABLE achi (
	id BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	title NVARCHAR(100) NOT NULL
);

GO

CREATE TABLE gameplayer (
	gameid BIGINT NOT NULL,
	playerid BIGINT NOT NULL
);

GO

CREATE TABLE statachi (
	statid BIGINT NOT NULL,
	achiid BIGINT NOT NULL
);

GO
